import type { IconName } from "@party-stack/icons";
import type { AndroidSymbol, SFSymbol } from "expo-symbols";

export interface ExpoSymbol {
    ios?: SFSymbol;
    android: AndroidSymbol;
}

export const ExpoSymbolNames: Record<IconName, ExpoSymbol> = {
    activity: { ios: "waveform.path.ecg", android: "ecg_heart" },
    add: { ios: "plus", android: "add" },
    airplane: { ios: "airplane", android: "flight" },
    alarm: { ios: "alarm", android: "alarm" },
    alert: { ios: "exclamationmark.circle", android: "error" },
    archive: { ios: "archivebox", android: "archive" },
    "arrow-down": { ios: "arrow.down", android: "arrow_downward" },
    "arrow-left": { ios: "arrow.left", android: "arrow_back" },
    "arrow-right": { ios: "arrow.right", android: "arrow_forward" },
    "arrow-up": { ios: "arrow.up", android: "arrow_upward" },
    attachment: { ios: "paperclip", android: "attach_file" },
    award: { ios: "medal", android: "workspace_premium" },
    bank: { ios: "building.columns", android: "account_balance" },
    barcode: { ios: "barcode", android: "barcode" },
    bell: { ios: "bell", android: "notifications" },
    book: { ios: "book", android: "menu_book" },
    bookmark: { ios: "bookmark", android: "bookmark" },
    briefcase: { ios: "briefcase", android: "work" },
    bug: { ios: "ladybug", android: "bug_report" },
    building: { ios: "building.2", android: "apartment" },
    calculator: { ios: "plus.forwardslash.minus", android: "calculate" },
    calendar: { ios: "calendar", android: "calendar_month" },
    camera: { ios: "camera", android: "photo_camera" },
    "chart-bar": { ios: "chart.bar", android: "bar_chart" },
    "chart-line": { ios: "chart.xyaxis.line", android: "show_chart" },
    "chart-pie": { ios: "chart.pie", android: "pie_chart" },
    chat: { ios: "message", android: "chat" },
    check: { ios: "checkmark", android: "check" },
    "check-circle": { ios: "checkmark.circle", android: "check_circle" },
    "chevron-down": { ios: "chevron.down", android: "expand_more" },
    "chevron-left": { ios: "chevron.left", android: "chevron_left" },
    "chevron-right": { ios: "chevron.right", android: "chevron_right" },
    "chevron-up": { ios: "chevron.up", android: "expand_less" },
    circle: { ios: "circle", android: "circle" },
    clipboard: { ios: "clipboard", android: "content_paste" },
    clock: { ios: "clock", android: "schedule" },
    cloud: { ios: "cloud", android: "cloud" },
    code: { ios: "chevron.left.forwardslash.chevron.right", android: "code" },
    compass: { ios: "safari", android: "explore" },
    copy: { ios: "doc.on.doc", android: "content_copy" },
    "credit-card": { ios: "creditcard", android: "credit_card" },
    cube: { ios: "cube", android: "deployed_code" },
    database: { ios: "cylinder", android: "database" },
    delete: { ios: "trash", android: "delete" },
    document: { ios: "doc", android: "description" },
    download: { ios: "arrow.down.to.line", android: "download" },
    edit: { ios: "pencil", android: "edit" },
    email: { ios: "envelope", android: "mail" },
    error: { ios: "exclamationmark.octagon", android: "error" },
    eye: { ios: "eye", android: "visibility" },
    "eye-off": { ios: "eye.slash", android: "visibility_off" },
    filter: { ios: "line.3.horizontal.decrease", android: "filter_alt" },
    flag: { ios: "flag", android: "flag" },
    folder: { ios: "folder", android: "folder" },
    globe: { ios: "globe", android: "public" },
    grid: { ios: "square.grid.2x2", android: "grid_view" },
    heart: { ios: "heart", android: "favorite" },
    help: { ios: "questionmark.circle", android: "help" },
    history: { ios: "clock.arrow.circlepath", android: "history" },
    home: { ios: "house", android: "home" },
    image: { ios: "photo", android: "image" },
    info: { ios: "info.circle", android: "info" },
    key: { ios: "key", android: "key" },
    layers: { ios: "square.3.layers.3d", android: "layers" },
    lightbulb: { ios: "lightbulb", android: "lightbulb" },
    link: { ios: "link", android: "link" },
    list: { ios: "list.bullet", android: "list" },
    location: { ios: "mappin.and.ellipse", android: "location_on" },
    lock: { ios: "lock", android: "lock" },
    "lock-open": { ios: "lock.open", android: "lock_open" },
    map: { ios: "map", android: "map" },
    menu: { ios: "line.3.horizontal", android: "menu" },
    microphone: { ios: "microphone", android: "mic" },
    minus: { ios: "minus", android: "remove" },
    "minus-circle": { ios: "minus.circle", android: "do_not_disturb_on" },
    moon: { ios: "moon", android: "dark_mode" },
    "more-horizontal": { ios: "ellipsis", android: "more_horiz" },
    "more-vertical": { ios: "ellipsis", android: "more_vert" },
    notification: { ios: "bell.badge", android: "notifications_active" },
    package: { ios: "shippingbox", android: "package_2" },
    pause: { ios: "pause", android: "pause" },
    people: { ios: "person.2", android: "group" },
    person: { ios: "person", android: "person" },
    phone: { ios: "phone", android: "call" },
    pin: { ios: "pin", android: "keep" },
    play: { ios: "play", android: "play_arrow" },
    "play-circle": { ios: "play.circle", android: "play_circle" },
    "plus-circle": { ios: "plus.circle", android: "add_circle" },
    printer: { ios: "printer", android: "print" },
    project: { ios: "folder.badge.gearshape", android: "folder_managed" },
    refresh: { ios: "arrow.clockwise", android: "refresh" },
    // The supplied SF Symbols snapshot has no rocket; do not substitute paperplane.
    rocket: { android: "rocket_launch" },
    save: { ios: "square.and.arrow.down", android: "save" },
    search: { ios: "magnifyingglass", android: "search" },
    send: { ios: "paperplane", android: "send" },
    settings: { ios: "gearshape", android: "settings" },
    share: { ios: "square.and.arrow.up", android: "share" },
    shield: { ios: "shield", android: "shield" },
    "shopping-bag": { ios: "bag", android: "shopping_bag" },
    "shopping-cart": { ios: "cart", android: "shopping_cart" },
    star: { ios: "star", android: "star" },
    stop: { ios: "stop", android: "stop" },
    sun: { ios: "sun.max", android: "light_mode" },
    tag: { ios: "tag", android: "sell" },
    ticket: { ios: "ticket", android: "confirmation_number" },
    tools: { ios: "wrench.and.screwdriver", android: "construction" },
    upload: { ios: "arrow.up.to.line", android: "upload" },
    video: { ios: "video", android: "videocam" },
    warning: { ios: "exclamationmark.triangle", android: "warning" },
    window: { ios: "macwindow", android: "web_asset" },
    wrench: { ios: "wrench", android: "build" },
    x: { ios: "xmark", android: "close" },
    "x-circle": { ios: "xmark.circle", android: "cancel" },
};

/**
 * Exact Material Symbols archive variants selected during visual review.
 * Runtime Expo identifiers remain in `ExpoSymbolNames`.
 */
export const MaterialSymbolArchiveNames: Partial<Record<IconName, string>> = {
    activity: "ecg-heart-outline",
    error: "error-outline-rounded",
    "minus-circle": "do-not-disturb-on-outline-rounded",
    pin: "keep-outline-rounded",
};

export function getExpoSymbol(name: IconName): ExpoSymbol {
    return ExpoSymbolNames[name];
}

export type { AndroidSymbol, SFSymbol };
