/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotesNoteIdRouteImport } from './routes/notes.$noteId'
import { Route as ApiRemoteOntologyEndpointRouteImport } from './routes/api.remote-ontology.$endpoint'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoteOntologyEndpointRoute =
  ApiRemoteOntologyEndpointRouteImport.update({
    id: '/api/remote-ontology/$endpoint',
    path: '/api/remote-ontology/$endpoint',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/api/remote-ontology/$endpoint': typeof ApiRemoteOntologyEndpointRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/api/remote-ontology/$endpoint': typeof ApiRemoteOntologyEndpointRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/api/remote-ontology/$endpoint': typeof ApiRemoteOntologyEndpointRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/notes/$noteId' | '/api/remote-ontology/$endpoint'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/notes/$noteId' | '/api/remote-ontology/$endpoint'
  id: '__root__' | '/' | '/notes/$noteId' | '/api/remote-ontology/$endpoint'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  ApiRemoteOntologyEndpointRoute: typeof ApiRemoteOntologyEndpointRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remote-ontology/$endpoint': {
      id: '/api/remote-ontology/$endpoint'
      path: '/api/remote-ontology/$endpoint'
      fullPath: '/api/remote-ontology/$endpoint'
      preLoaderRoute: typeof ApiRemoteOntologyEndpointRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  ApiRemoteOntologyEndpointRoute: ApiRemoteOntologyEndpointRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
