/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObjectTypesObjectTypeRouteImport } from './routes/object-types.$objectType'
import { Route as LinkTypesLinkTypeRouteImport } from './routes/link-types.$linkType'
import { Route as ActionTypesActionTypeRouteImport } from './routes/action-types.$actionType'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectTypesObjectTypeRoute = ObjectTypesObjectTypeRouteImport.update({
  id: '/object-types/$objectType',
  path: '/object-types/$objectType',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkTypesLinkTypeRoute = LinkTypesLinkTypeRouteImport.update({
  id: '/link-types/$linkType',
  path: '/link-types/$linkType',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionTypesActionTypeRoute = ActionTypesActionTypeRouteImport.update({
  id: '/action-types/$actionType',
  path: '/action-types/$actionType',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/action-types/$actionType': typeof ActionTypesActionTypeRoute
  '/link-types/$linkType': typeof LinkTypesLinkTypeRoute
  '/object-types/$objectType': typeof ObjectTypesObjectTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/action-types/$actionType': typeof ActionTypesActionTypeRoute
  '/link-types/$linkType': typeof LinkTypesLinkTypeRoute
  '/object-types/$objectType': typeof ObjectTypesObjectTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/action-types/$actionType': typeof ActionTypesActionTypeRoute
  '/link-types/$linkType': typeof LinkTypesLinkTypeRoute
  '/object-types/$objectType': typeof ObjectTypesObjectTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/action-types/$actionType'
    | '/link-types/$linkType'
    | '/object-types/$objectType'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/action-types/$actionType'
    | '/link-types/$linkType'
    | '/object-types/$objectType'
  id:
    | '__root__'
    | '/'
    | '/action-types/$actionType'
    | '/link-types/$linkType'
    | '/object-types/$objectType'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionTypesActionTypeRoute: typeof ActionTypesActionTypeRoute
  LinkTypesLinkTypeRoute: typeof LinkTypesLinkTypeRoute
  ObjectTypesObjectTypeRoute: typeof ObjectTypesObjectTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/object-types/$objectType': {
      id: '/object-types/$objectType'
      path: '/object-types/$objectType'
      fullPath: '/object-types/$objectType'
      preLoaderRoute: typeof ObjectTypesObjectTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link-types/$linkType': {
      id: '/link-types/$linkType'
      path: '/link-types/$linkType'
      fullPath: '/link-types/$linkType'
      preLoaderRoute: typeof LinkTypesLinkTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action-types/$actionType': {
      id: '/action-types/$actionType'
      path: '/action-types/$actionType'
      fullPath: '/action-types/$actionType'
      preLoaderRoute: typeof ActionTypesActionTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionTypesActionTypeRoute: ActionTypesActionTypeRoute,
  LinkTypesLinkTypeRoute: LinkTypesLinkTypeRoute,
  ObjectTypesObjectTypeRoute: ObjectTypesObjectTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
