/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiRemoteOntologyEndpointRouteImport } from './routes/api.remote-ontology.$endpoint'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoteOntologyEndpointRoute =
  ApiRemoteOntologyEndpointRouteImport.update({
    id: '/api/remote-ontology/$endpoint',
    path: '/api/remote-ontology/$endpoint',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/remote-ontology/$endpoint': typeof ApiRemoteOntologyEndpointRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/remote-ontology/$endpoint': typeof ApiRemoteOntologyEndpointRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/remote-ontology/$endpoint': typeof ApiRemoteOntologyEndpointRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/project/$projectId'
    | '/api/auth/$'
    | '/api/remote-ontology/$endpoint'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/project/$projectId'
    | '/api/auth/$'
    | '/api/remote-ontology/$endpoint'
  id:
    | '__root__'
    | '/'
    | '/auth/callback'
    | '/project/$projectId'
    | '/api/auth/$'
    | '/api/remote-ontology/$endpoint'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRemoteOntologyEndpointRoute: typeof ApiRemoteOntologyEndpointRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remote-ontology/$endpoint': {
      id: '/api/remote-ontology/$endpoint'
      path: '/api/remote-ontology/$endpoint'
      fullPath: '/api/remote-ontology/$endpoint'
      preLoaderRoute: typeof ApiRemoteOntologyEndpointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRemoteOntologyEndpointRoute: ApiRemoteOntologyEndpointRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
